### ISSUE TITLE
half translated kucoe_github_io

### ISSUE THREAD

**Issue by azerdudukyan** [kucoe/kucoe#1]
>>after downloading jar you can run it with command
after downloading jar you can run it with a command

>>later you can save this command into bash/cmd file and place intto your environment to run it with simple "elvn" command after start, 
>>elvn will show you a list of planned tasks and interactive command prompt.
>>learn more about elvn in theory here
Later you can save this command into a bash/cmd file and place it into your environment to run it with a simple "elvn" command after start,
elvn will show you a list of planned tasks and an interactive command prompt.
Learn more about elvn in theory here.

>>elvn provides opportunity to manage 7 projects organized in lists of tasks and 3 system lists
elvn provides an opportunity to manage 7 projects organized in lists of tasks and 3 system lists.
The? system lists are:

>>project's lists are indentified by color name and label, if assigned
Project lists are identified by color, name and label,? if assigned

>>by default only blue (Work) and green (Personal) project lists are enabled
By default only the? blue (Work) and the? green (Personal) project lists are enabled.

>>to list your projects use '&' command, when projects are listed you can edit them
To list your projects use an? '&' command, when the? projects are listed you can edit them.

>>to enable project you need to assign label to project, do this by entering project color (one-character format is acceptable) and label separated by colon, in this way you can change project's label
To enable a project you need to assign a label to the? project, do this by entering the? project color (one-character format is acceptable) and the? label separated by a? colon, this way you can change the project label.

>>to disable project you need to remove label from project, do this by entering project color (one-character format is acceptable) and colon without label
аналогічно складне речення

>>you can switch between lists using '/{c(olor)}' or '/{label}' or '/a(ll)', '/t(oday)', '/d(one)' commands
You can switch between the lists using...

>>elvn provides particular list for ideas, which are not related to projects but just stored in one stack
Elvn provides a particular list for ideas which are not related to the projects but are just?/ stored/are stored in one stack.

>>1.good idea
>>2.better idea
1. A good idea
2. A better idea

**Comment by becevka** [comment]
https://github.com/kucoe/elvn/issues/10 Moved to correct project
