### ISSUE TITLE
Onboarding: Missing embedded image in email

### ISSUE THREAD

**Issue by azerdudukyan** [kucoe/kucoe#3]
Confirmation e-mail.
An empty LogoImage frame is shown, src attribute missing. 
![kucoe_registration_mail_no_image](https://user-images.githubusercontent.com/29871085/28374325-0f97b0dc-6cad-11e7-9da2-6a3a74742abd.jpg)

**Comment by becevka** [comment]
Interesting, I got such email, when tried to create new room.
<img width="634" alt="screen shot 2017-07-10 at 9 30 19 pm" src="https://user-images.githubusercontent.com/2912772/28048508-0b8e2dec-65b7-11e7-8678-5b4985253be8.PNG">

**Comment by becevka** [comment]
Fixed.
